Vagrant.require_version ">= 1.7.0"

def set_vbox(vb, config)
  vb.gui = false
  vb.memory = 2048
  vb.cpus = 1
  config.vm.box = "k2r2bai/kubeadm-ubuntu18"
end

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  master = 1
  node = 2

  private_count = 10
  (1..(master + node)).each do |mid|
    name = (mid <= node) ? "n" : "m"
    id   = (mid <= node) ? mid : (mid - node)

    config.vm.define "k8s-#{name}#{id}" do |n|
      n.vm.hostname = "k8s-#{name}#{id}"
      ip_addr = "192.16.35.#{private_count}"
      n.vm.network :private_network, ip: "#{ip_addr}",  auto_config: true
      n.vm.provider :virtualbox do |vb, override|
        vb.name = "#{n.vm.hostname}"
        set_vbox(vb, override)
      end
      private_count += 1
      n.vm.provision "shell", inline: "sudo swapoff -a && sudo sysctl -w vm.swappiness=0"
      n.vm.provision "shell", inline: <<-SHELL
        echo "127.0.0.1       localhost

192.16.35.10    k8s-n1
192.16.35.11    k8s-n2
192.16.35.12    k8s-m1
192.16.35.99    k8s-harbor

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters" | sudo tee /etc/hosts
      SHELL
    end
  end
end