apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns
  name: coredns-tcp
  namespace: ddns
spec:
  type: LoadBalancer
  externalIPs:
  - 192.16.35.12
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
  selector:
    k8s-app: coredns
  
