apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns
  name: coredns-udp
  namespace: ddns
spec:
  type: LoadBalancer
  externalIPs:
  - 192.16.35.12
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  selector:
    k8s-app: coredns
  
